# Generated by Django 5.0.6 on 2024-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=200, verbose_name="비밀번호"),
        ),
    ]
