# Generated by Django 5.0.6 on 2024-08-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_of_week", models.CharField(blank=True, max_length=10, null=True)),
                ("week_of_month", models.IntegerField(blank=True, null=True)),
                ("mood_completed", models.BooleanField(default=False)),
                ("exercise_completed", models.BooleanField(default=False)),
                ("happiness_completed", models.BooleanField(default=False)),
                ("diet_completed", models.BooleanField(default=False)),
                ("all_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
