# Generated by Django 5.0.6 on 2024-08-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyinfo",
            name="diet_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyinfo",
            name="exercise_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyinfo",
            name="happiness_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyinfo",
            name="mood_mission",
            field=models.TextField(blank=True, null=True),
        ),
    ]
