# Generated by Django 5.0.6 on 2024-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(choices=[("남", "남성"), ("여", "여성")], max_length=1),
        ),
    ]
