# Generated by Django 5.0.6 on 2024-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                max_length=150,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="사용자 ID",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=50, verbose_name="이름"),
        ),
    ]
