# Generated by Django 5.0.6 on 2024-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_survey_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_member",
            field=models.BooleanField(default=True, verbose_name="회원 여부"),
        ),
    ]
