name: Deploy to cloudtype
on:
  push:
    branches:
      - develop7
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dailyoriental/dailyoriental
          stage: main
          yaml: |
            name: dailyoriental-be

            app: python@3.12

            options:
              env:
                - name: DJANGO_SECRET
                  value: 5xeuu%71e@wu=#f@^xs6fp0d$adc@c7dvk@8-gfb%0r@ynpe*-
                - name: ApiKey
                  value: sk-proj-qfsDsWgY3ytBXpC4Yz2ET3BlbkFJdS2BONj19hexFstEFOEd
                - name: DJANGO_SUPERUSER_USERNAME
                  value: daily
                - name: DJANGO_SUPERUSER_PASSWORD
                  value: "1111"
                - name: DJANGO_SUPERUSER_EMAIL
                  value: daily@gmail.com
              ports: 8000
              start: python3 manage.py runserver 0:8000
              buildenv: []
              prestart: python3 manage.py makemigrations && python3 manage.py migrate
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
